package hcmute.edu.vn.id18110304.Daos;

import java.util.Arrays;
import java.util.List;

import hcmute.edu.vn.id18110304.Domains.CountryDomain;
import hcmute.edu.vn.id18110304.Interfaces.IGenericDao;
import hcmute.edu.vn.id18110304.R;

public class CountryDao implements IGenericDao {

   private static CountryDao instance = null;

   private CountryDao() {
   }

   public static CountryDao getInstance() {
      if (instance == null) {
         instance = new CountryDao();
      }
      return instance;
   }

   @Override
   public List<CountryDomain> getAll() {
      return Arrays.asList(
            new CountryDomain("Afghanistan", "93", "af", "afg", R.drawable.z_flag_af),
            new CountryDomain("Albania", "355", "al", "alb", R.drawable.z_flag_al),
            new CountryDomain("Algeria", "213", "dz", "dza", R.drawable.z_flag_dz),
            new CountryDomain("American Samoa", "1-684", "as", "asm", R.drawable.z_flag_as),
            new CountryDomain("Andorra", "376", "ad", "and", R.drawable.z_flag_ad),
            new CountryDomain("Angola", "244", "ao", "ago", R.drawable.z_flag_ao),
            new CountryDomain("Anguilla", "1-264", "ai", "aia", R.drawable.z_flag_ai),
            //new CountryDomain("Antarctica", "672", "aq", "ata", R.drawable.z_flag_aq),
            new CountryDomain("Antigua and Barbuda", "1-268", "ag", "atg", R.drawable.z_flag_ag),
            new CountryDomain("Argentina", "54", "ar", "arg", R.drawable.z_flag_ar),
            new CountryDomain("Armenia", "374", "am", "arm", R.drawable.z_flag_am),
            new CountryDomain("Aruba", "297", "aw", "abw", R.drawable.z_flag_aw),
            new CountryDomain("Australia", "61", "au", "aus", R.drawable.z_flag_au),
            new CountryDomain("Austria", "43", "at", "aut", R.drawable.z_flag_at),
            new CountryDomain("Azerbaijan", "994", "az", "aze", R.drawable.z_flag_az),
            new CountryDomain("Bahamas", "1-242", "bs", "bhs", R.drawable.z_flag_bs),
            new CountryDomain("Bahrain", "973", "bh", "bhr", R.drawable.z_flag_bh),
            new CountryDomain("Bangladesh", "880", "bd", "bgd", R.drawable.z_flag_bd),
            new CountryDomain("Barbados", "1-246", "bb", "brb", R.drawable.z_flag_bb),
            new CountryDomain("Belarus", "375", "by", "blr", R.drawable.z_flag_by),
            new CountryDomain("Belgium", "32", "be", "bel", R.drawable.z_flag_be),
            new CountryDomain("Belize", "501", "bz", "blz", R.drawable.z_flag_bz),
            new CountryDomain("Benin", "229", "bj", "ben", R.drawable.z_flag_bj),
            new CountryDomain("Bermuda", "1-441", "bm", "bmu", R.drawable.z_flag_bm),
            new CountryDomain("Bhutan", "975", "bt", "btn", R.drawable.z_flag_bt),
            new CountryDomain("Bolivia", "591", "bo", "bol", R.drawable.z_flag_bo),
            new CountryDomain("Bosnia and Herzegovina", "387", "ba", "bih", R.drawable.z_flag_ba),
            new CountryDomain("Botswana", "267", "bw", "bwa", R.drawable.z_flag_bw),
            new CountryDomain("Brazil", "55", "br", "bra", R.drawable.z_flag_br),
            new CountryDomain("British Indian Ocean Territory", "246", "io", "iot", R.drawable.z_flag_io),
            new CountryDomain("British Virgin Islands", "1-284", "vg", "vgb", R.drawable.z_flag_vg),
            new CountryDomain("Brunei", "673", "bn", "brn", R.drawable.z_flag_bn),
            new CountryDomain("Bulgaria", "359", "bg", "bgr", R.drawable.z_flag_bg),
            new CountryDomain("Burkina Faso", "226", "bf", "bfa", R.drawable.z_flag_bf),
            new CountryDomain("Burundi", "257", "bi", "bdi", R.drawable.z_flag_bi),
            new CountryDomain("Cambodia", "855", "kh", "khm", R.drawable.z_flag_kh),
            new CountryDomain("Cameroon", "237", "cm", "cmr", R.drawable.z_flag_cm),
            new CountryDomain("Canada", "1", "ca", "can", R.drawable.z_flag_ca),
            new CountryDomain("Cape Verde", "238", "cv", "cpv", R.drawable.z_flag_cv),
            new CountryDomain("Cayman Islands", "1-345", "ky", "cym", R.drawable.z_flag_ky),
            new CountryDomain("Central African Republic", "236", "cf", "caf", R.drawable.z_flag_cf),
            new CountryDomain("Chad", "235", "td", "tcd", R.drawable.z_flag_td),
            new CountryDomain("Chile", "56", "cl", "chl", R.drawable.z_flag_cl),
            new CountryDomain("China", "86", "cn", "chn", R.drawable.z_flag_cn),
            new CountryDomain("Christmas Island", "61", "cx", "cxr", R.drawable.z_flag_cx),
            new CountryDomain("Cocos Islands", "61", "cc", "cck", R.drawable.z_flag_cc),
            new CountryDomain("Colombia", "57", "co", "col", R.drawable.z_flag_co),
            new CountryDomain("Comoros", "269", "km", "com", R.drawable.z_flag_km),
            new CountryDomain("Cook Islands", "682", "ck", "cok", R.drawable.z_flag_ck),
            new CountryDomain("Costa Rica", "506", "cr", "cri", R.drawable.z_flag_cr),
            new CountryDomain("Croatia", "385", "hr", "hrv", R.drawable.z_flag_hr),
            new CountryDomain("Cuba", "53", "cu", "cub", R.drawable.z_flag_cu),
            new CountryDomain("Curacao", "599", "cw", "cuw", R.drawable.z_flag_cw),
            new CountryDomain("Cyprus", "357", "cy", "cyp", R.drawable.z_flag_cy),
            new CountryDomain("Czech Republic", "420", "cz", "cze", R.drawable.z_flag_cz),
            new CountryDomain("Democratic Republic of the Congo", "243", "cd", "cod", R.drawable.z_flag_cd),
            new CountryDomain("Denmark", "45", "dk", "dnk", R.drawable.z_flag_dk),
            new CountryDomain("Djibouti", "253", "dj", "dji", R.drawable.z_flag_dj),
            new CountryDomain("Dominica", "1-767", "dm", "dma", R.drawable.z_flag_dm),
            new CountryDomain("Dominican Republic", "1-809, 1-829, 1-849", "do", "dom", R.drawable.z_flag_do),
            new CountryDomain("East Timor", "670", "tl", "tls", R.drawable.z_flag_tl),
            new CountryDomain("Ecuador", "593", "ec", "ecu", R.drawable.z_flag_ec),
            new CountryDomain("Egypt", "20", "eg", "egy", R.drawable.z_flag_eg),
            new CountryDomain("El Salvador", "503", "sv", "slv", R.drawable.z_flag_sv),
            new CountryDomain("Equatorial Guinea", "240", "gq", "gnq", R.drawable.z_flag_gq),
            new CountryDomain("Eritrea", "291", "er", "eri", R.drawable.z_flag_er),
            new CountryDomain("Estonia", "372", "ee", "est", R.drawable.z_flag_ee),
            new CountryDomain("Ethiopia", "251", "et", "eth", R.drawable.z_flag_et),
            new CountryDomain("Falkland Islands", "500", "fk", "flk", R.drawable.z_flag_fk),
            new CountryDomain("Faroe Islands", "298", "fo", "fro", R.drawable.z_flag_fo),
            new CountryDomain("Fiji", "679", "fj", "fji", R.drawable.z_flag_fj),
            new CountryDomain("Finland", "358", "fi", "fin", R.drawable.z_flag_fi),
            new CountryDomain("France", "33", "fr", "fra", R.drawable.z_flag_fr),
            new CountryDomain("French Polynesia", "689", "pf", "pyf", R.drawable.z_flag_pf),
            new CountryDomain("Gabon", "241", "ga", "gab", R.drawable.z_flag_ga),
            new CountryDomain("Gambia", "220", "gm", "gmb", R.drawable.z_flag_gm),
            new CountryDomain("Georgia", "995", "ge", "geo", R.drawable.z_flag_ge),
            new CountryDomain("Germany", "49", "de", "deu", R.drawable.z_flag_de),
            new CountryDomain("Ghana", "233", "gh", "gha", R.drawable.z_flag_gh),
            new CountryDomain("Gibraltar", "350", "gi", "gib", R.drawable.z_flag_gi),
            new CountryDomain("Greece", "30", "gr", "grc", R.drawable.z_flag_gr),
            new CountryDomain("Greenland", "299", "gl", "grl", R.drawable.z_flag_gl),
            new CountryDomain("Grenada", "1-473", "gd", "grd", R.drawable.z_flag_gd),
            new CountryDomain("Guam", "1-671", "gu", "gum", R.drawable.z_flag_gu),
            new CountryDomain("Guatemala", "502", "gt", "gtm", R.drawable.z_flag_gt),
            new CountryDomain("Guernsey", "44-1481", "gg", "ggy", R.drawable.z_flag_gg),
            new CountryDomain("Guinea", "224", "gn", "gin", R.drawable.z_flag_gn),
            new CountryDomain("Guinea-Bissau", "245", "gw", "gnb", R.drawable.z_flag_gw),
            new CountryDomain("Guyana", "592", "gy", "guy", R.drawable.z_flag_gy),
            new CountryDomain("Haiti", "509", "ht", "hti", R.drawable.z_flag_ht),
            new CountryDomain("Honduras", "504", "hn", "hnd", R.drawable.z_flag_hn),
            new CountryDomain("Hong Kong", "852", "hk", "hkg", R.drawable.z_flag_hk),
            new CountryDomain("Hungary", "36", "hu", "hun", R.drawable.z_flag_hu),
            new CountryDomain("Iceland", "354", "is", "isl", R.drawable.z_flag_is),
            new CountryDomain("India", "91", "in", "ind", R.drawable.z_flag_in),
            new CountryDomain("Indonesia", "62", "id", "idn", R.drawable.z_flag_id),
            new CountryDomain("Iran", "98", "ir", "irn", R.drawable.z_flag_ir),
            new CountryDomain("Iraq", "964", "iq", "irq", R.drawable.z_flag_iq),
            new CountryDomain("Ireland", "353", "ie", "irl", R.drawable.z_flag_ie),
            new CountryDomain("Isle of Man", "44-1624", "im", "imn", R.drawable.z_flag_im),
            new CountryDomain("Israel", "972", "il", "isr", R.drawable.z_flag_il),
            new CountryDomain("Italy", "39", "it", "ita", R.drawable.z_flag_it),
            new CountryDomain("Ivory Coast", "225", "ci", "civ", R.drawable.z_flag_ci),
            new CountryDomain("Jamaica", "1-876", "jm", "jam", R.drawable.z_flag_jm),
            new CountryDomain("Japan", "81", "jp", "jpn", R.drawable.z_flag_jp),
            new CountryDomain("Jersey", "44-1534", "je", "jey", R.drawable.z_flag_je),
            new CountryDomain("Jordan", "962", "jo", "jor", R.drawable.z_flag_jo),
            new CountryDomain("Kazakhstan", "7", "kz", "kaz", R.drawable.z_flag_kz),
            new CountryDomain("Kenya", "254", "ke", "ken", R.drawable.z_flag_ke),
            new CountryDomain("Kiribati", "686", "ki", "kir", R.drawable.z_flag_ki),
            new CountryDomain("Kosovo", "383", "xk", "xkx", R.drawable.z_flag_xk),
            new CountryDomain("Kuwait", "965", "kw", "kwt", R.drawable.z_flag_kw),
            new CountryDomain("Kyrgyzstan", "996", "kg", "kgz", R.drawable.z_flag_kg),
            new CountryDomain("Laos", "856", "la", "lao", R.drawable.z_flag_la),
            new CountryDomain("Latvia", "371", "lv", "lva", R.drawable.z_flag_lv),
            new CountryDomain("Lebanon", "961", "lb", "lbn", R.drawable.z_flag_lb),
            new CountryDomain("Lesotho", "266", "ls", "lso", R.drawable.z_flag_ls),
            new CountryDomain("Liberia", "231", "lr", "lbr", R.drawable.z_flag_lr),
            new CountryDomain("Libya", "218", "ly", "lby", R.drawable.z_flag_ly),
            new CountryDomain("Liechtenstein", "423", "li", "lie", R.drawable.z_flag_li),
            new CountryDomain("Lithuania", "370", "lt", "ltu", R.drawable.z_flag_lt),
            new CountryDomain("Luxembourg", "352", "lu", "lux", R.drawable.z_flag_lu),
            new CountryDomain("Macau", "853", "mo", "mac", R.drawable.z_flag_mo),
            new CountryDomain("Macedonia", "389", "mk", "mkd", R.drawable.z_flag_mk),
            new CountryDomain("Madagascar", "261", "mg", "mdg", R.drawable.z_flag_mg),
            new CountryDomain("Malawi", "265", "mw", "mwi", R.drawable.z_flag_mw),
            new CountryDomain("Malaysia", "60", "my", "mys", R.drawable.z_flag_my),
            new CountryDomain("Maldives", "960", "mv", "mdv", R.drawable.z_flag_mv),
            new CountryDomain("Mali", "223", "ml", "mli", R.drawable.z_flag_ml),
            new CountryDomain("Malta", "356", "mt", "mlt", R.drawable.z_flag_mt),
            new CountryDomain("Marshall Islands", "692", "mh", "mhl", R.drawable.z_flag_mh),
            new CountryDomain("Mauritania", "222", "mr", "mrt", R.drawable.z_flag_mr),
            new CountryDomain("Mauritius", "230", "mu", "mus", R.drawable.z_flag_mu),
            new CountryDomain("Mayotte", "262", "yt", "myt", R.drawable.z_flag_yt),
            new CountryDomain("Mexico", "52", "mx", "mex", R.drawable.z_flag_mx),
            new CountryDomain("Micronesia", "691", "fm", "fsm", R.drawable.z_flag_fm),
            new CountryDomain("Moldova", "373", "md", "mda", R.drawable.z_flag_md),
            new CountryDomain("Monaco", "377", "mc", "mco", R.drawable.z_flag_mc),
            new CountryDomain("Mongolia", "976", "mn", "mng", R.drawable.z_flag_mn),
            new CountryDomain("Montenegro", "382", "me", "mne", R.drawable.z_flag_me),
            new CountryDomain("Montserrat", "1-664", "ms", "msr", R.drawable.z_flag_ms),
            new CountryDomain("Morocco", "212", "ma", "mar", R.drawable.z_flag_ma),
            new CountryDomain("Mozambique", "258", "mz", "moz", R.drawable.z_flag_mz),
            new CountryDomain("Myanmar", "95", "mm", "mmr", R.drawable.z_flag_mm),
            new CountryDomain("Namibia", "264", "na", "nam", R.drawable.z_flag_na),
            new CountryDomain("Nauru", "674", "nr", "nru", R.drawable.z_flag_nr),
            new CountryDomain("Nepal", "977", "np", "npl", R.drawable.z_flag_np),
            new CountryDomain("Netherlands", "31", "nl", "nld", R.drawable.z_flag_nl),
            //new CountryDomain("Netherlands Antilles", "599", "an", "ant", R.drawable.z_flag_an),
            new CountryDomain("New Caledonia", "687", "nc", "ncl", R.drawable.z_flag_nc),
            new CountryDomain("New Zealand", "64", "nz", "nzl", R.drawable.z_flag_nz),
            new CountryDomain("Nicaragua", "505", "ni", "nic", R.drawable.z_flag_ni),
            new CountryDomain("Niger", "227", "ne", "ner", R.drawable.z_flag_ne),
            new CountryDomain("Nigeria", "234", "ng", "nga", R.drawable.z_flag_ng),
            new CountryDomain("Niue", "683", "nu", "niu", R.drawable.z_flag_nu),
            new CountryDomain("North Korea", "850", "kp", "prk", R.drawable.z_flag_kp),
            new CountryDomain("Northern Mariana Islands", "1-670", "mp", "mnp", R.drawable.z_flag_mp),
            new CountryDomain("Norway", "47", "no", "nor", R.drawable.z_flag_no),
            new CountryDomain("Oman", "968", "om", "omn", R.drawable.z_flag_om),
            new CountryDomain("Pakistan", "92", "pk", "pak", R.drawable.z_flag_pk),
            new CountryDomain("Palau", "680", "pw", "plw", R.drawable.z_flag_pw),
            new CountryDomain("Palestine", "970", "ps", "pse", R.drawable.z_flag_ps),
            new CountryDomain("Panama", "507", "pa", "pan", R.drawable.z_flag_pa),
            new CountryDomain("Papua New Guinea", "675", "pg", "png", R.drawable.z_flag_pg),
            new CountryDomain("Paraguay", "595", "py", "pry", R.drawable.z_flag_py),
            new CountryDomain("Peru", "51", "pe", "per", R.drawable.z_flag_pe),
            new CountryDomain("Philippines", "63", "ph", "phl", R.drawable.z_flag_ph),
            new CountryDomain("Pitcairn", "64", "pn", "pcn", R.drawable.z_flag_pn),
            new CountryDomain("Poland", "48", "pl", "pol", R.drawable.z_flag_pl),
            new CountryDomain("Portugal", "351", "pt", "prt", R.drawable.z_flag_pt),
            new CountryDomain("Puerto Rico", "1-787, 1-939", "pr", "pri", R.drawable.z_flag_pr),
            new CountryDomain("Qatar", "974", "qa", "qat", R.drawable.z_flag_qa),
            new CountryDomain("Republic of the Congo", "242", "cg", "cog", R.drawable.z_flag_cg),
            new CountryDomain("Reunion", "262", "re", "reu", R.drawable.z_flag_re),
            new CountryDomain("Romania", "40", "ro", "rou", R.drawable.z_flag_ro),
            new CountryDomain("Russia", "7", "ru", "rus", R.drawable.z_flag_ru),
            new CountryDomain("Rwanda", "250", "rw", "rwa", R.drawable.z_flag_rw),
            new CountryDomain("Saint Barthelemy", "590", "bl", "blm", R.drawable.z_flag_bl),
            new CountryDomain("Saint Helena", "290", "sh", "shn", R.drawable.z_flag_sh),
            new CountryDomain("Saint Kitts and Nevis", "1-869", "kn", "kna", R.drawable.z_flag_kn),
            new CountryDomain("Saint Lucia", "1-758", "lc", "lca", R.drawable.z_flag_lc),
            new CountryDomain("Saint Martin", "590", "mf", "maf", R.drawable.z_flag_mf),
            new CountryDomain("Saint Pierre and Miquelon", "508", "pm", "spm", R.drawable.z_flag_pm),
            new CountryDomain("Saint Vincent and the Grenadines", "1-784", "vc", "vct", R.drawable.z_flag_vc),
            new CountryDomain("Samoa", "685", "ws", "wsm", R.drawable.z_flag_ws),
            new CountryDomain("San Marino", "378", "sm", "smr", R.drawable.z_flag_sm),
            new CountryDomain("Sao Tome and Principe", "239", "st", "stp", R.drawable.z_flag_st),
            new CountryDomain("Saudi Arabia", "966", "sa", "sau", R.drawable.z_flag_sa),
            new CountryDomain("Senegal", "221", "sn", "sen", R.drawable.z_flag_sn),
            new CountryDomain("Serbia", "381", "rs", "srb", R.drawable.z_flag_rs),
            new CountryDomain("Seychelles", "248", "sc", "syc", R.drawable.z_flag_sc),
            new CountryDomain("Sierra Leone", "232", "sl", "sle", R.drawable.z_flag_sl),
            new CountryDomain("Singapore", "65", "sg", "sgp", R.drawable.z_flag_sg),
            new CountryDomain("Sint Maarten", "1-721", "sx", "sxm", R.drawable.z_flag_sx),
            new CountryDomain("Slovakia", "421", "sk", "svk", R.drawable.z_flag_sk),
            new CountryDomain("Slovenia", "386", "si", "svn", R.drawable.z_flag_si),
            new CountryDomain("Solomon Islands", "677", "sb", "slb", R.drawable.z_flag_sb),
            new CountryDomain("Somalia", "252", "so", "som", R.drawable.z_flag_so),
            new CountryDomain("South Africa", "27", "za", "zaf", R.drawable.z_flag_za),
            new CountryDomain("South Korea", "82", "kr", "kor", R.drawable.z_flag_kr),
            new CountryDomain("South Sudan", "211", "ss", "ssd", R.drawable.z_flag_ss),
            new CountryDomain("Spain", "34", "es", "esp", R.drawable.z_flag_es),
            new CountryDomain("Sri Lanka", "94", "lk", "lka", R.drawable.z_flag_lk),
            new CountryDomain("Sudan", "249", "sd", "sdn", R.drawable.z_flag_sd),
            new CountryDomain("Suriname", "597", "sr", "sur", R.drawable.z_flag_sr),
            new CountryDomain("Svalbard and Jan Mayen", "47", "sj", "sjm", R.drawable.z_flag_sj),
            new CountryDomain("Swaziland", "268", "sz", "swz", R.drawable.z_flag_sz),
            new CountryDomain("Sweden", "46", "se", "swe", R.drawable.z_flag_se),
            new CountryDomain("Switzerland", "41", "ch", "che", R.drawable.z_flag_ch),
            new CountryDomain("Syria", "963", "sy", "syr", R.drawable.z_flag_sy),
            new CountryDomain("Taiwan", "886", "tw", "twn", R.drawable.z_flag_tw),
            new CountryDomain("Tajikistan", "992", "tj", "tjk", R.drawable.z_flag_tj),
            new CountryDomain("Tanzania", "255", "tz", "tza", R.drawable.z_flag_tz),
            new CountryDomain("Thailand", "66", "th", "tha", R.drawable.z_flag_th),
            new CountryDomain("Togo", "228", "tg", "tgo", R.drawable.z_flag_tg),
            new CountryDomain("Tokelau", "690", "tk", "tkl", R.drawable.z_flag_tk),
            new CountryDomain("Tonga", "676", "to", "ton", R.drawable.z_flag_to),
            new CountryDomain("Trinidad and Tobago", "1-868", "tt", "tto", R.drawable.z_flag_tt),
            new CountryDomain("Tunisia", "216", "tn", "tun", R.drawable.z_flag_tn),
            new CountryDomain("Turkey", "90", "tr", "tur", R.drawable.z_flag_tr),
            new CountryDomain("Turkmenistan", "993", "tm", "tkm", R.drawable.z_flag_tm),
            new CountryDomain("Turks and Caicos Islands", "1-649", "tc", "tca", R.drawable.z_flag_tc),
            new CountryDomain("Tuvalu", "688", "tv", "tuv", R.drawable.z_flag_tv),
            new CountryDomain("U.S. Virgin Islands", "1-340", "vi", "vir", R.drawable.z_flag_vi),
            new CountryDomain("Uganda", "256", "ug", "uga", R.drawable.z_flag_ug),
            new CountryDomain("Ukraine", "380", "ua", "ukr", R.drawable.z_flag_ua),
            new CountryDomain("United Arab Emirates", "971", "ae", "are", R.drawable.z_flag_ae),
            new CountryDomain("United Kingdom", "44", "gb", "gbr", R.drawable.z_flag_gb),
            new CountryDomain("United States", "1", "us", "usa", R.drawable.z_flag_us),
            new CountryDomain("Uruguay", "598", "uy", "ury", R.drawable.z_flag_uy),
            new CountryDomain("Uzbekistan", "998", "uz", "uzb", R.drawable.z_flag_uz),
            new CountryDomain("Vanuatu", "678", "vu", "vut", R.drawable.z_flag_vu),
            new CountryDomain("Vatican", "379", "va", "vat", R.drawable.z_flag_va),
            new CountryDomain("Venezuela", "58", "ve", "ven", R.drawable.z_flag_ve),
            new CountryDomain("Vietnam", "84", "vn", "vnm", R.drawable.z_flag_vn),
            new CountryDomain("Wallis and Futuna", "681", "wf", "wlf", R.drawable.z_flag_wf),
            //new CountryDomain("Western Sahara", "212", "eh", "esh", R.drawable.z_flag_eh),
            new CountryDomain("Yemen", "967", "ye", "yem", R.drawable.z_flag_ye),
            new CountryDomain("Zambia", "260", "zm", "zmb", R.drawable.z_flag_zm),
            new CountryDomain("Zimbabwe", "263", "zw", "zwe", R.drawable.z_flag_zw)
      );
   }

   @Override
   public List getById(Object id) {
      return null;
   }

   @Override
   public boolean update(Object object) {
      return false;
   }

   @Override
   public boolean delete(Object id) {
      return false;
   }
}
